kind: PersistentVolume
apiVersion: v1
metadata:
  name: elasticsearch-pv-volume
  namespace: kube-system
  labels:
    type: local
    app: elasticsearch
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 5Gi
  accessModes: [ "ReadWriteOnce" ]
  local:
    path: "/run/desktop/mnt/host/d/k8s.storage/elasticsearch"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop    
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticsearch-pv-claim
  namespace: kube-system  
  labels:
    app: elasticsearch
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi