apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: facturascripts
  labels:
    app: facturascripts
spec:
  replicas: 1
  serviceName: "facturascripts"
  selector:
    matchLabels:
      app: facturascripts
  template:
    metadata:
      labels:
        app: facturascripts
    spec:
      containers:
      - name: facturascripts
        image: facturascripts/facturascripts:2021.71
        ports:
           - containerPort: 80
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: shared-data
          mountPath: "/var/www/html"
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: facturascripts-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: facturascripts
  labels:
    app: facturascripts
spec:
  type: NodePort
  ports:
   - port: 80
  selector:
   app: facturascripts
  externalIPs: ["192.168.0.10"]        