kind: PersistentVolume
apiVersion: v1
metadata:
  name: facturascripts-pv-volume
  labels:
    type: local
    app: facturascripts
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  local:
    path: "/run/desktop/mnt/host/c/k8s.storage/facturascripts"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: facturascripts-pv-claim
  labels:
    app: facturascripts
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi