apiVersion: v1
kind: Pod
metadata:
  name: utilities
  labels:
    app: utilities
spec:
  restartPolicy: Always
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["/bin/bash", "-c"]
    args:
      - /scripts/utilities.sh;
        /bin/sleep 3650d
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volume-from-config-map-script
      mountPath: "/scripts"
      readOnly: true
  - name: adminer
    image: adminer
    ports:
      - containerPort: 8080
    envFrom:
      - configMapRef:
          name: cm-utilities
  volumes:
  - name: volume-from-config-map-script
    projected:
      sources:
      - configMap:
          name: cm-utilities
          items:
          - key: utilities.sh
            path: utilities.sh
            mode: 0755
---
apiVersion: v1
kind: Service
metadata:
  name: utilities
  labels:
    app: utilities
spec:
  type: NodePort
  ports:
   - port: 8080
  selector:
   app: utilities
  externalIPs: ["192.168.0.34"]