apiVersion: batch/v1
kind: CronJob
metadata:
  name: dwh
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pentahopdi
            image: bame/pentahopdi:9.3
            imagePullPolicy: IfNotPresent
            envFrom:
              - configMapRef: 
                  name: cm-pentahopdi
            env:
              - name: JOB_NAME
                value: "DWH"
              - name: JOB_PARAMS
                value: "-param:full_load=Y -param:initial_load=Y -level:Debug"
          restartPolicy: Never